package com.qdu.pojo;
// Generated 2017-6-14 14:47:15 by Hibernate Tools 4.3.1



/**
 * OrderDetails generated by hbm2java
 */
public class OrderDetails  implements java.io.Serializable {


     private int orderDetailsId;
     private OrderList orderList;
     private Product product;
     private int orderedQty;

    public OrderDetails() {
    }

    public OrderDetails(int orderDetailsId, OrderList orderList, Product product, int orderedQty) {
       this.orderDetailsId = orderDetailsId;
       this.orderList = orderList;
       this.product = product;
       this.orderedQty = orderedQty;
    }
   
    public int getOrderDetailsId() {
        return this.orderDetailsId;
    }
    
    public void setOrderDetailsId(int orderDetailsId) {
        this.orderDetailsId = orderDetailsId;
    }
    public OrderList getOrderList() {
        return this.orderList;
    }
    
    public void setOrderList(OrderList orderList) {
        this.orderList = orderList;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public int getOrderedQty() {
        return this.orderedQty;
    }
    
    public void setOrderedQty(int orderedQty) {
        this.orderedQty = orderedQty;
    }




}


