package com.qdu.pojo;
// Generated 2017-6-14 14:47:15 by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.sql.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * OrderList generated by hbm2java
 */
public class OrderList  implements java.io.Serializable {


     private int orderId;
     private Users users;
     private Date orderTime;
     private int orderStatus;
     private Set orderDetailses = new HashSet(0);

    public OrderList() {
    }

	
    public OrderList(int orderId, Users users, Date orderTime, int orderStatus) {
        this.orderId = orderId;
        this.users = users;
        this.orderTime = orderTime;
        this.orderStatus = orderStatus;
    }
    public OrderList(int orderId, Users users, Date orderTime, int orderStatus, Set orderDetailses) {
       this.orderId = orderId;
       this.users = users;
       this.orderTime = orderTime;
       this.orderStatus = orderStatus;
       this.orderDetailses = orderDetailses;
    }
   
    public int getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(int orderId) {
        this.orderId = orderId;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public Serializable getOrderTime() {
        return this.orderTime;
    }
    
    public void setOrderTime(Date orderTime) {
        this.orderTime = orderTime;
    }
    public int getOrderStatus() {
        return this.orderStatus;
    }
    
    public void setOrderStatus(int orderStatus) {
        this.orderStatus = orderStatus;
    }
    public Set getOrderDetailses() {
        return this.orderDetailses;
    }
    
    public void setOrderDetailses(Set orderDetailses) {
        this.orderDetailses = orderDetailses;
    }




}


