package com.qdu.pojo;
// Generated 2017-6-14 14:47:15 by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.sql.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Product generated by hbm2java
 */
public class Product  implements java.io.Serializable {

     private int productId;
     private ProductCategory productCategory;
     private String productName;
     private double productPrice;
     private int productStore;
     private String productImagePath;
     private String productDetails;
     private Date addProductDate;
     private Set orderDetailses = new HashSet(0);
     private Set productHelpers = new HashSet(0);

    public Product() {
    }

	
    public Product(int productId, ProductCategory productCategory, String productName, double productPrice, int productStore, String productImagePath, String productDetails, Date addProductDate) {
        this.productId = productId;
        this.productCategory = productCategory;
        this.productName = productName;
        this.productPrice = productPrice;
        this.productStore = productStore;
        this.productImagePath = productImagePath;
        this.productDetails = productDetails;
        this.addProductDate = addProductDate;
    }
    public Product(int productId, ProductCategory productCategory, String productName, double productPrice, int productStore, String productImagePath, String productDetails, Date addProductDate, Set orderDetailses, Set productHelpers) {
       this.productId = productId;
       this.productCategory = productCategory;
       this.productName = productName;
       this.productPrice = productPrice;
       this.productStore = productStore;
       this.productImagePath = productImagePath;
       this.productDetails = productDetails;
       this.addProductDate = addProductDate;
       this.orderDetailses = orderDetailses;
       this.productHelpers = productHelpers;
    }
   
    public int getProductId() {
        return this.productId;
    }
    
    public void setProductId(int productId) {
        this.productId = productId;
    }
    public ProductCategory getProductCategory() {
        return this.productCategory;
    }
    
    public void setProductCategory(ProductCategory productCategory) {
        this.productCategory = productCategory;
    }
    public String getProductName() {
        return this.productName;
    }
    
    public void setProductName(String productName) {
        this.productName = productName;
    }
    public double getProductPrice() {
        return this.productPrice;
    }
    
    public void setProductPrice(double productPrice) {
        this.productPrice = productPrice;
    }
    public int getProductStore() {
        return this.productStore;
    }
    
    public void setProductStore(int productStore) {
        this.productStore = productStore;
    }
    public String getProductImagePath() {
        return this.productImagePath;
    }
    
    public void setProductImagePath(String productImagePath) {
        this.productImagePath = productImagePath;
    }
    public String getProductDetails() {
        return this.productDetails;
    }
    
    public void setProductDetails(String productDetails) {
        this.productDetails = productDetails;
    }
    public Serializable getAddProductDate() {
        return this.addProductDate;
    }
    
    public void setAddProductDate(Date addProductDate) {
        this.addProductDate = addProductDate;
    }
    public Set getOrderDetailses() {
        return this.orderDetailses;
    }
     
    public void setOrderDetailses(Set orderDetailses) {
        this.orderDetailses = orderDetailses;
    }
    public Set getProductHelpers() {
        return this.productHelpers;
    }
    
    public void setProductHelpers(Set productHelpers) {
        this.productHelpers = productHelpers;
    }




}


