package com.qdu.pojo;
// Generated 2017-6-14 14:47:15 by Hibernate Tools 4.3.1



/**
 * ProductHelper generated by hbm2java
 */
public class ProductHelper  implements java.io.Serializable {


     private int id;
     private Product product;
     private SalesPromotion salesPromotion;

    public ProductHelper() {
    }

	
    public ProductHelper(int id) {
        this.id = id;
    }
    public ProductHelper(int id, Product product, SalesPromotion salesPromotion) {
       this.id = id;
       this.product = product;
       this.salesPromotion = salesPromotion;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public SalesPromotion getSalesPromotion() {
        return this.salesPromotion;
    }
    
    public void setSalesPromotion(SalesPromotion salesPromotion) {
        this.salesPromotion = salesPromotion;
    }




}


