package com.qdu.pojo;
// Generated 2017-6-14 14:47:15 by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * SalesPromotion generated by hbm2java
 */
public class SalesPromotion  implements java.io.Serializable {


     private int salesId;
     private int salesPromotion;
     private Serializable salesBegin;
     private Serializable salesEnd;
     private Double salesDiscount;
     private String salesTitle;
     private Set productHelpers = new HashSet(0);

    public SalesPromotion() {
    }

	
    public SalesPromotion(int salesId, int salesPromotion, Serializable salesBegin, Serializable salesEnd) {
        this.salesId = salesId;
        this.salesPromotion = salesPromotion;
        this.salesBegin = salesBegin;
        this.salesEnd = salesEnd;
    }
    public SalesPromotion(int salesId, int salesPromotion, Serializable salesBegin, Serializable salesEnd, Double salesDiscount, String salesTitle, Set productHelpers) {
       this.salesId = salesId;
       this.salesPromotion = salesPromotion;
       this.salesBegin = salesBegin;
       this.salesEnd = salesEnd;
       this.salesDiscount = salesDiscount;
       this.salesTitle = salesTitle;
       this.productHelpers = productHelpers;
    }
   
    public int getSalesId() {
        return this.salesId;
    }
    
    public void setSalesId(int salesId) {
        this.salesId = salesId;
    }
    public int getSalesPromotion() {
        return this.salesPromotion;
    }
    
    public void setSalesPromotion(int salesPromotion) {
        this.salesPromotion = salesPromotion;
    }
    public Serializable getSalesBegin() {
        return this.salesBegin;
    }
    
    public void setSalesBegin(Serializable salesBegin) {
        this.salesBegin = salesBegin;
    }
    public Serializable getSalesEnd() {
        return this.salesEnd;
    }
    
    public void setSalesEnd(Serializable salesEnd) {
        this.salesEnd = salesEnd;
    }
    public Double getSalesDiscount() {
        return this.salesDiscount;
    }
    
    public void setSalesDiscount(Double salesDiscount) {
        this.salesDiscount = salesDiscount;
    }
    public String getSalesTitle() {
        return this.salesTitle;
    }
    
    public void setSalesTitle(String salesTitle) {
        this.salesTitle = salesTitle;
    }
    public Set getProductHelpers() {
        return this.productHelpers;
    }
    
    public void setProductHelpers(Set productHelpers) {
        this.productHelpers = productHelpers;
    }




}


