package com.qdu.pojo;
// Generated 2017-6-14 14:47:15 by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private String userId;
     private String userName;
     private String userPassword;
     private String userGender;
     private String userPhone;
     private String userAddress;
     private String userAccount;
     private double userBalance;
     private Set orderLists = new HashSet(0);

    public Users() {
    }

	
    public Users(String userId, String userName, String userPassword, String userGender, String userPhone, String userAddress, String userAccount, double userBalance) {
        this.userId = userId;
        this.userName = userName;
        this.userPassword = userPassword;
        this.userGender = userGender;
        this.userPhone = userPhone;
        this.userAddress = userAddress;
        this.userAccount = userAccount;
        this.userBalance = userBalance;
    }
    public Users(String userId, String userName, String userPassword, String userGender, String userPhone, String userAddress, String userAccount, double userBalance, Set orderLists) {
       this.userId = userId;
       this.userName = userName;
       this.userPassword = userPassword;
       this.userGender = userGender;
       this.userPhone = userPhone;
       this.userAddress = userAddress;
       this.userAccount = userAccount;
       this.userBalance = userBalance;
       this.orderLists = orderLists;
    }
   
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }
    public Serializable getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getUserPassword() {
        return this.userPassword;
    }
    
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword;
    }
    public String getUserGender() {
        return this.userGender;
    }
    
    public void setUserGender(String userGender) {
        this.userGender = userGender;
    }
    public String getUserPhone() {
        return this.userPhone;
    }
    
    public void setUserPhone(String userPhone) {
        this.userPhone = userPhone;
    }
    public Serializable getUserAddress() {
        return this.userAddress;
    }
    
    public void setUserAddress(String userAddress) {
        this.userAddress = userAddress;
    }
    public String getUserAccount() {
        return this.userAccount;
    }
    
    public void setUserAccount(String userAccount) {
        this.userAccount = userAccount;
    }
    public double getUserBalance() {
        return this.userBalance;
    }
    
    public void setUserBalance(double userBalance) {
        this.userBalance = userBalance;
    }
    public Set getOrderLists() {
        return this.orderLists;
    }
    
    public void setOrderLists(Set orderLists) {
        this.orderLists = orderLists;
    }
}


